# Generated by Django 5.0.3 on 2024-04-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='media/course_images/default.png', upload_to='media/course_images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='proof_of_course',
            field=models.FileField(default='media/course_proof/default1712473172.20471.png', upload_to='media/course_proof'),
        ),
    ]
