# Generated by Django 5.0.3 on 2024-04-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_review_proof_of_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='proof_of_course',
            field=models.FileField(upload_to=''),
        ),
    ]
