# Generated by Django 5.0.3 on 2024-04-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_course_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
