# Generated by Django 5.0.3 on 2024-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_course_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_desc',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
